import Navbar from '../components/Navbar';
import Head from 'next/head';

import HeroPage from './HeroPage';
import SocialLinks from '../components/SocialLinks';
import Portfolio from '../components/Portfolio';
import Services from '../components/Services';
import Contact from '../components/Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Apollonia | Portofolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <main className=' bg-background px-10 md:px-20 lg:px-40 dark:bg-bgDark'>
        <HeroPage />
        <SocialLinks />
        <Portfolio />
        <Services />
        <Contact />
      </main>
    </div>
  );
}
